python updates
additions:
* python3-dukpy (0.5.1)
* python3-dulwich (0.24.6)
* python3-giturlparse (0.12.0)
* python3-jsonpath-ng (1.8.0)
* python3-pypac (0.17.2)
* python3-python-discovery (1.1.3)
* python3-python-rule-engine (1.0.0)
* python3-python-win-ad (0.6.2)
* python3-qgis-deployment-toolbelt (0.40.0)
* python3-requests-file (3.0.1)
* python3-tldextract (5.3.1)
* python3-truststore (0.10.4)

updates:
* python3-pytz (2025.2-1 -> 2026.1.post1-1)
* python3-lazy-loader (0.4 -> 0.5)
* python3-async-lru (2.1.0 -> 2.2.0)
* python3-blosc2 (4.0.0 -> 4.1.2)
* python3-certifi (2026.1.4 -> 2026.2.25)
* python3-chardet (5.2.0 -> 7.1.0)
* python3-duckdb (1.4.4 -> 1.5.0)
* python3-filelock (3.24.3 -> 3.25.2)
* python3-fonttools (4.61.1 -> 4.62.1)
* python3-ipython (9.10.0 -> 9.11.0)
* python3-isort (7.0.0 -> 8.0.1)
* python3-kiwisolver (1.4.9 -> 1.5.0)
* python3-narwhals (2.16.0 -> 2.18.0)
* python3-nose2 (0.15.1 -> 0.16.0)
* python3-pgserviceparser (2.5.0 -> 3.0.3)
* python3-plotly (6.5.2 -> 6.6.0)
* python3-pum (1.5.3 -> 1.6.2)
* python3-quantecon (0.10.1 -> 0.11.1)
* python3-regex (2026.1.15 -> 2026.2.28)
* python3-tables (3.10.2 -> 3.11.1)
* python3-virtualenv (20.38.0 -> 21.2.0)

patches:
* python3-charset-normalizer (3.4.4->5)
* python3-esda (2.8.1->2)
* python3-geoalchemy2 (0.18.1->4)
* python3-geopandas (1.1.2->3)
* python3-greenlet (3.3.1->2)
* python3-jupyterlab (4.5.4->6)
* python3-maturin (1.12.3->6)
* python3-nltk (3.9.2->3)
* python3-notebook (7.5.3->5)
* python3-numpy (2.4.2->3)
* python3-platformdirs (4.9.2->4)
* python3-pointpats (2.5.2->5)
* python3-pyqt6-sip (13.11.0->1)
* python3-scipy (1.17.0->1)
* python3-setuptools (82.0.0->1)
* python3-sip (6.15.1-1->2)
* python3-sqlalchemy (2.0.46->48)
* python3-tornado (6.5.4->5)
* python3-werkzeug (3.1.5->6)

downgrade:
* python3-packaging (26.0 -> 25.0; requirement of qgis-deployment-toolbelt 0.40.0)

diff --git a/scripts/build-helpers b/scripts/build-helpers
--- a/scripts/build-helpers
+++ b/scripts/build-helpers
@@ -31,6 +31,7 @@ log() {
 declare -x log
 
 startlog() {
+	log_failed=0
 	echo "Local package repository: $OSGEO4W_REP"
 	echo "Logging to $OSGEO4W_PWD/package.log"
 	savelog package.log
@@ -114,12 +115,16 @@ faillog() {
 	if [ -f "$OSGEO4W_SCRIPTS/fail" ]; then
 		bash "$OSGEO4W_SCRIPTS/fail"
 	fi
+	log_failed=1
 	finishlog
 	return 1
 }
 declare -x faillog
 
 finishlog() {
+	if (( log_failed == 0 )) && [ -f "$OSGEO4W_SCRIPTS/success" ]; then
+		bash "$OSGEO4W_SCRIPTS/success"
+	fi
 	if [ -f "$OSGEO4W_SCRIPTS/finish" ]; then
 		bash "$OSGEO4W_SCRIPTS/finish"
 	fi
@@ -147,8 +152,9 @@ fetchenv() {
 
 	! [ -f $d/log ] || cat $d/log
 
+	# locked while it's running
 	while [ -f $d/log ]; do
-		rm $d/log || sleep 2
+		rm $d/log 2>/dev/null || sleep 2
 	done
 
 	cat <<EOF >|$d/envdiff
@@ -668,6 +674,25 @@ nextbinary() {
 }
 declare -x nextbinary
 
+pinnedpypkgs() {
+	local i
+
+	echo -ne "^Package\s+.*\\n|^-.*\\n|^\\.\\n"
+	for i in $OSGEO4W_SCRIPTS/../src/python3-*/osgeo4w/package.sh
+	do
+		P=
+		V=
+		eval $(head -2 $i)
+		[ -n "$P" -a -n "$V" ] || { echo "$i: P or V not found"; exit 1; }
+
+		[ "$V" != pip ] || continue
+		p=${P#python3-}
+		p=${p//-/[_-]}
+		echo -ne "|^$p\s+${V//./\\.}\s+.*\\n"
+	done
+}
+declare -x pinnedpypkg
+
 packagewheel() {
 	log "Packaging $P==$V with pip"
 
@@ -730,23 +755,8 @@ packagewheel() {
 
 		set | grep "^PIP_"
 
-		if [ -z "$OSGEO4W_PY_PINNED_RE" ]; then
-			export OSGEO4W_PY_PINNED_RE=$(
-				echo -ne "^Package\s+.*\\n|^-.*\\n|^\\.\\n"
-				for i in $OSGEO4W_PWD/../../python3-*/osgeo4w/package.sh
-				do
-					P=
-					V=
-					eval $(head -2 $i)
-					[ -n "$P" -a -n "$V" ] || { echo "$i: P or V not found"; exit 1; }
-
-					[ "$V" != pip ] || continue
-					p=${P#python3-}
-					p=${p//-/[_-]}
-					echo -ne "|^$p\s+${V//./\\.}\s+.*\\n"
-				done
-			)
-		fi
+		export OSGEO4W_PY_PINNED_RE
+		[ -n "$OSGEO4W_PY_PINNED_RE" ] || OSGEO4W_PY_PINNED_RE=$(pinnedpypkgs)
 
 		echo "PINNED: $OSGEO4W_PY_PINNED_RE"
 
